### PR TITLE
Fixed compatibility with TypeScript 3.9.6

### LINKED ISSUE #7: Project fails to compile above TypeScript 3.8.x
Upgrading the version of TypeScript used to compile this project past 3.8.x results in the following error on `yarn build`:

```
$ tsc
src/mocking.ts:141:13 - error TS2589: Type instantiation is excessively deep and possibly infinite.

141         id: this.id,
                ~~~~~~~


Found 1 error.
```

Reproduction steps:

```
git checkout master
yarn install
yarn add -D typescript@3.9.6
yarn build
```

### PR DESCRIPTION
**Pull request by brisberg**
Fixes #7 

Upgrading the version of TypeScript used to compile this project past 3.8.x results in the following error on `yarn build`:

```
$ tsc
src/mocking.ts:141:13 - error TS2589: Type instantiation is excessively deep and possibly infinite.

141         id: this.id,
                ~~~~~~~


Found 1 error.
```

The issue here being that reusing `this.id` causes a recursive type definition on `id` (also on `structureType` on the next line).

Removing the references to `this` in the `toJson` function and instead relying on a function closure flattens the type definition. Allowing this project to compile with typescript@latest (3.9.6).

Also, I had to change the TestEnvironment export in `index.ts` from a `* export` to an `import` with a `default export`. Otherwise Jest could not find the test environment.

---

If you approve this change, and merge this PR, can you bump the version in `package.json` and add a new git tag? I'd like to be able to depend on a specific version instead of master.

### CODE REVIEW

File: src/mocking.ts [hunk 1]
```diff
@@ -133,14 +133,12 @@ function mockStructure<T extends StructureConstant>(structureType: T, mockedProp
   const count = (structureCounters[structureType] ?? 0) + 1;
 
   structureCounters[structureType] = count;
+  const id = `${structureType}${count}` as Id<ConcreteStructure<T>>;
```
Comment (brisberg) [inline src/mocking.ts:136]: Performing this calculation one and locking down the type removed the recursive typing.

File: index.ts [hunk 2]
```diff
@@ -1,2 +1,4 @@
-export { mockGlobal, mockInstanceOf, mockStructure } from "./src/mocking";
-export * from "./src/TestEnvironment";
+import TestEnvironment from './src/TestEnvironment';
+
+export {mockGlobal, mockInstanceOf, mockStructure} from './src/mocking';
+export default TestEnvironment;
```
Comment (brisberg) [inline index.ts:4]: Default exports worked slightly differently in TS 3.9

**Comment by brisberg** [comment]
Friendly ping on this. Have you had a chance to check it out?

**Comment by eduter** [comment]
No, I didn't look at it yet. This is my last week of vacation and I've been staying away from coding. From next week, I'll have less time, but I'll be in coding mode again, so I intend to look at it then.

**Comment by brisberg** [comment]
Sounds good, take your time. Just wanted to make sure this didn't drop off your radar. 😄
